/**
 * app/services/suggestions/types.ts
 *
 * Internal types shared across the suggestion engine modules.
 * Not exported outside the suggestions service — consumers use the
 * public Suggestion type from app/data/schema.ts.
 */

import type {
  Plant,
  Seedling,
  GardenEventType,
  Priority,
  SuggestionType,
  SuggestionScope,
} from "../../data/schema";
import type { PlacedPlant } from "../gardenState";
import type { WeatherData } from "../weather";

export type { PlacedPlant } from "../gardenState";

// ---------------------------------------------------------------------------
// Rule context — built once per evaluation run
// ---------------------------------------------------------------------------

export interface RuleContext {
  /** Current month 1–12 (1 = January). */
  currentMonth: number;
  /** Today's date at midnight UTC for age calculations. */
  today: Date;
  /** Active UI locale used for localized suggestion text. */
  locale?: string;
  /** Köppen–Geiger zone code from settings.growthZone, e.g. "Cfb". */
  koeppenZone: string;
  lat?: number;
  lng?: number;
  /** All plant instances placed across all areas + planters. */
  placedPlants: PlacedPlant[];
  /** All active seedling batches. */
  seedlings: Seedling[];
  /**
   * Last event timestamps, keyed by `${planterId}:${instanceId}` → GardenEventType → Date.
   * For garden-wide events (e.g. weeding a whole planter) the instanceId part is "global".
   */
  lastEvents: Map<string, Map<GardenEventType, Date>>;
  /** Live weather data, or null when operating offline / no location set. */
  weather: WeatherData | null;
}

// ---------------------------------------------------------------------------
// Rule result types
// ---------------------------------------------------------------------------

export interface SuggestionResult {
  /**
   * Deterministic key used for de-duplication and stable IDs.
   * Format: `${ruleId}:${planterId}:${instanceId}` or `${ruleId}:global`
   */
  key: string;
  type: SuggestionType;
  plant?: Plant;
  planterId?: string;
  instanceId?: string;
  priority: Priority;
  description: string;
  /** ISO datetime. */
  dueDate?: string;
  /** ISO datetime — auto-dismiss after this point. */
  expiresAt?: string;
  source: "rules";
  ruleId: string;
  /** Area ID this suggestion applies to (for planter-wide suggestions). */
  areaId?: string;
  /** Human-readable area name for display in the journal and suggestions panel. */
  areaName?: string;
  /** Human-readable planter name for display. */
  planterName?: string;
  /** Explicit scope of the suggestion target. */
  scope?: SuggestionScope;
}

export interface AISuggestionResult {
  type: SuggestionType;
  plant?: Plant;
  planterId?: string;
  instanceId?: string;
  priority: Priority;
  description: string;
  dueDate?: string;
  source: "ai";
  /** Area ID for area-scoped AI suggestions. */
  areaId?: string;
  /** Human-readable area name. */
  areaName?: string;
  /** Human-readable planter name. */
  planterName?: string;
  /** Explicit scope of the suggestion target. */
  scope?: SuggestionScope;
}

// ---------------------------------------------------------------------------
// AI context (serialised and sent to OpenRouter)
// ---------------------------------------------------------------------------

export interface AISuggestionContextPlant {
  name: string;
  displayName: string;
  areaName: string;
  planterName: string;
  plantedDaysAgo?: number;
  daysToHarvest?: number;
  harvestMonths: number[];
  sowDirectMonths: number[];
  companions: string[];
  antagonists: string[];
  adjacentPlants: string[];
  adjacentPlantDisplayNames: string[];
}

export interface AISuggestionContextSeedling {
  name: string;
  displayName: string;
  status: string;
  daysSinceSeeded: number;
}

export interface AISuggestionContextEvent {
  type: string;
  daysAgo: number;
  areaName?: string;
  planterName?: string;
}

export interface AISuggestionContext {
  koeppenZone: string;
  hemisphere: "N" | "S";
  currentMonth: number;
  lat?: number;
  lng?: number;
  responseLocale: "en" | "nl";
  responseLanguage: string;
  /** AI model used to generate this batch — included in the cache key. */
  model: string;
  weather: {
    todayTempMaxC: number;
    todayPrecipMm: number;
    next7DaysMaxTempC: number;
    next7DaysMinTempC: number;
    next7DaysTotalPrecipMm: number;
    next7DaysPrecipProbMax: number;
  } | null;
  plants: AISuggestionContextPlant[];
  seedlings: AISuggestionContextSeedling[];
  recentEvents: AISuggestionContextEvent[];
  /** Suggestion keys already generated by the rules engine (to avoid duplication). */
  activeRuleSuggestionKeys: string[];
}

// ---------------------------------------------------------------------------
// Raw AI response shape (before mapping to Suggestion[])
// ---------------------------------------------------------------------------

export interface RawAISuggestion {
  type: string;
  plantName?: string | null;
  planterName?: string | null;
  /** Area name — used for area-scoped suggestions mentioning sensitive plants. */
  areaName?: string | null;
  priority: string;
  description: string;
  dueDate?: string | null;
  rationale: string;
  confidence: number;
  /** Target scope declared by the AI. */
  scope?: string | null;
}

export interface AISuggestionsResponse {
  suggestions: RawAISuggestion[];
}
