/**
 * app/hooks/useGardenEvents.ts
 *
 * Manages garden events, including:
 * - Adding / removing plant events when plants are added / removed
 * - Completing a suggestion (logs the corresponding event)
 * - Deriving the harvestAlerts list from placed plants
 *
 * NOTE: Suggestions are now generated by useSuggestions (the rules engine +
 * AI). This hook only handles event logging and harvest alerts derived from
 * placed plants with known harvest dates.
 */

import type { GardenRepository } from "../data/repository";
import type { GardenEvent as SchemaGardenEvent } from "../data/schema";
import type { PlantInstance } from "../components/PlanterGrid";
import type { GardenEvent, Suggestion } from "../components/EventsBar";
import {
  dismissErrorToast,
  ERROR_TOAST_IDS,
  notifyErrorToast,
} from "../lib/asyncErrors";

export interface GardenEventsState {
  harvestAlerts: Array<{
    plantName: string;
    plantIcon: string;
    daysUntilHarvest: number;
    areaName: string;
  }>;
  handlePlantAdded: (plantInstance: PlantInstance, planterId: string) => void;
  handlePlantRemoved: (
    plantInstance: PlantInstance,
    planterId: string,
    eventType?: "harvested" | "removed",
  ) => void;
  handlePlantUpdated: (
    plantInstance: PlantInstance,
    previousPlantInstance: PlantInstance | null,
    planterId: string,
  ) => void;
  handleCompleteSuggestion: (suggestion: Suggestion) => void;
}

interface UseGardenEventsParams {
  setEvents: React.Dispatch<React.SetStateAction<GardenEvent[]>>;
  repositoryRef: React.MutableRefObject<GardenRepository>;
}

export function useGardenEvents({
  setEvents,
  repositoryRef,
}: UseGardenEventsParams): GardenEventsState {
  // harvestAlerts is now an empty array — derived from areas/planters in the
  // suggestion engine. Kept here for backward compatibility with EventsBar props.
  const harvestAlerts: GardenEventsState["harvestAlerts"] = [];

  const handlePlantAdded = (
    plantInstance: PlantInstance,
    planterId: string,
  ) => {
    const eventLog: GardenEvent = {
      id: `planted-${Date.now()}-${Math.random()}`,
      type: "planted",
      plant: plantInstance.plant,
      date: new Date().toISOString(),
      gardenId: planterId,
    };
    setEvents((prev) => [eventLog, ...prev]);
    void repositoryRef.current.saveEvent(
      eventLog as unknown as SchemaGardenEvent,
    )
      .then(() => dismissErrorToast(ERROR_TOAST_IDS.eventsSync))
      .catch((error) => {
        notifyErrorToast({
          id: ERROR_TOAST_IDS.eventsSync,
          title: "Could not save garden event",
          error,
          fallback: "The journal entry may not be fully persisted.",
        });
      });
  };

  const handlePlantRemoved = (
    plantInstance: PlantInstance,
    planterId: string,
    eventType: "harvested" | "removed" = "harvested",
  ) => {
    const eventLog: GardenEvent = {
      id: `${eventType}-${Date.now()}-${Math.random()}`,
      type: eventType,
      plant: plantInstance.plant,
      date: new Date().toISOString(),
      gardenId: planterId,
    };
    setEvents((prev) => [eventLog, ...prev]);
    void repositoryRef.current.saveEvent(
      eventLog as unknown as SchemaGardenEvent,
    )
      .then(() => dismissErrorToast(ERROR_TOAST_IDS.eventsSync))
      .catch((error) => {
        notifyErrorToast({
          id: ERROR_TOAST_IDS.eventsSync,
          title: "Could not save garden event",
          error,
          fallback: "The journal entry may not be fully persisted.",
        });
      });
  };

  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  const handlePlantUpdated = (
    plantInstance: PlantInstance,
    previousPlantInstance: PlantInstance | null,
    planterId: string,
  ) => {
    const previousEventIds = new Set(
      (previousPlantInstance?.pestEvents ?? []).map((event) => event.id),
    );
    const addedPestEvents = (plantInstance.pestEvents ?? []).filter(
      (event) => !previousEventIds.has(event.id),
    );

    if (addedPestEvents.length === 0) return;

    const journalEntries: GardenEvent[] = addedPestEvents.map((event) => ({
      id: `${event.type}-${event.id}`,
      type: event.type,
      plant: plantInstance.plant,
      date: event.date,
      gardenId: planterId,
      note: event.description,
    }));

    setEvents((prev) => [...journalEntries, ...prev]);
    void Promise.all(
      journalEntries.map((entry) =>
        repositoryRef.current.saveEvent(entry as unknown as SchemaGardenEvent),
      ),
    )
      .then(() => dismissErrorToast(ERROR_TOAST_IDS.eventsSync))
      .catch((error) => {
        console.error("[Events] Failed to save pest journal entries:", error);
        notifyErrorToast({
          id: ERROR_TOAST_IDS.eventsSync,
          title: "Could not save pest history",
          error,
          fallback: "The pest journal update may not be fully persisted.",
        });
      });
  };

  const handleCompleteSuggestion = (suggestion: Suggestion) => {
    // Map suggestion type → event type for the journal log
    const eventType: GardenEvent["type"] =
      suggestion.type === "water"
        ? "watered"
        : suggestion.type === "harvest"
          ? "harvested"
          : suggestion.type === "treatment"
            ? "treatment"
            : suggestion.type === "fertilize" || suggestion.type === "compost"
              ? "composted"
              : suggestion.type === "weed"
                ? "weeded"
                : suggestion.type === "sow" ||
                    suggestion.type === "succession_sow"
                  ? "sown"
                  : "composted";

    const completedEvent: GardenEvent = {
      id: `event-${Date.now()}-${Math.random()}`,
      type: eventType,
      plant: suggestion.plant,
      date: new Date().toISOString(),
      gardenId: suggestion.planterId,
      note:
        suggestion.type === "treatment" ? suggestion.description : undefined,
    };
    setEvents((prev) => [completedEvent, ...prev]);
    void repositoryRef.current.saveEvent(
      completedEvent as unknown as SchemaGardenEvent,
    )
      .then(() => dismissErrorToast(ERROR_TOAST_IDS.eventsSync))
      .catch((error) => {
        notifyErrorToast({
          id: ERROR_TOAST_IDS.eventsSync,
          title: "Could not save completed suggestion",
          error,
          fallback: "The completed action may not be fully persisted.",
        });
      });
  };

  return {
    harvestAlerts,
    handlePlantAdded,
    handlePlantRemoved,
    handlePlantUpdated,
    handleCompleteSuggestion,
  };
}
