/**
 * app/hooks/useGardenEvents.ts
 *
 * Manages garden events, including:
 * - Adding / removing plant events when plants are added / removed
 * - Completing a suggestion (logs the corresponding event)
 * - Deriving the harvestAlerts list from placed plants
 *
 * NOTE: Suggestions are now generated by useSuggestions (the rules engine +
 * AI). This hook only handles event logging and harvest alerts derived from
 * placed plants with known harvest dates.
 */

import type { GardenRepository } from "../data/repository";
import type { GardenEvent as SchemaGardenEvent } from "../data/schema";
import type { PlantInstance } from "../components/PlanterGrid";
import type { GardenEvent, Suggestion } from "../components/EventsBar";
import {
  dismissErrorToast,
  ERROR_TOAST_IDS,
  notifyErrorToast,
} from "../lib/asyncErrors";

export interface GardenEventsState {
  harvestAlerts: Array<{
    plantName: string;
    plantIcon: string;
    daysUntilHarvest: number;
    areaName: string;
  }>;
  handlePlantAdded: (plantInstance: PlantInstance, planterId: string) => void;
  handlePlantRemoved: (
    plantInstance: PlantInstance,
    planterId: string,
    eventType?: "harvested" | "removed",
  ) => void;
  handlePlantUpdated: (
    plantInstance: PlantInstance,
    previousPlantInstance: PlantInstance | null,
    planterId: string,
  ) => void;
  handleCompleteSuggestion: (suggestion: Suggestion) => void;
  /** Log a planter-level maintenance action (watered, weeded, etc.). */
  handlePlanterAction: (params: {
    type: GardenEvent["type"];
    planterId: string;
    areaId?: string;
    planterName?: string;
    areaName?: string;
    note?: string;
  }) => void;
  /** Log an area-level action and generate synthetic planter-scope entries. */
  handleAreaAction: (params: {
    type: GardenEvent["type"];
    areaId: string;
    areaName: string;
    planterIds: string[];
    planterNames: string[];
    note?: string;
  }) => void;
}

interface UseGardenEventsParams {
  setEvents: React.Dispatch<React.SetStateAction<GardenEvent[]>>;
  repositoryRef: React.MutableRefObject<GardenRepository>;
}

export function useGardenEvents({
  setEvents,
  repositoryRef,
}: UseGardenEventsParams): GardenEventsState {
  // harvestAlerts is now an empty array — derived from areas/planters in the
  // suggestion engine. Kept here for backward compatibility with EventsBar props.
  const harvestAlerts: GardenEventsState["harvestAlerts"] = [];

  const handlePlantAdded = (
    plantInstance: PlantInstance,
    planterId: string,
  ) => {
    const eventLog: GardenEvent = {
      id: `planted-${Date.now()}-${Math.random()}`,
      type: "planted",
      plant: plantInstance.plant,
      date: new Date().toISOString(),
      gardenId: planterId,
      instanceId: plantInstance.instanceId,
    };
    setEvents((prev) => [eventLog, ...prev]);
    void repositoryRef.current.saveEvent(
      eventLog as unknown as SchemaGardenEvent,
    )
      .then(() => dismissErrorToast(ERROR_TOAST_IDS.eventsSync))
      .catch((error) => {
        notifyErrorToast({
          id: ERROR_TOAST_IDS.eventsSync,
          title: "Could not save garden event",
          error,
          fallback: "The journal entry may not be fully persisted.",
        });
      });
  };

  const handlePlantRemoved = (
    plantInstance: PlantInstance,
    planterId: string,
    eventType: "harvested" | "removed" = "harvested",
  ) => {
    const eventLog: GardenEvent = {
      id: `${eventType}-${Date.now()}-${Math.random()}`,
      type: eventType,
      plant: plantInstance.plant,
      date: new Date().toISOString(),
      gardenId: planterId,
      instanceId: plantInstance.instanceId,
    };
    setEvents((prev) => [eventLog, ...prev]);
    void repositoryRef.current.saveEvent(
      eventLog as unknown as SchemaGardenEvent,
    )
      .then(() => dismissErrorToast(ERROR_TOAST_IDS.eventsSync))
      .catch((error) => {
        notifyErrorToast({
          id: ERROR_TOAST_IDS.eventsSync,
          title: "Could not save garden event",
          error,
          fallback: "The journal entry may not be fully persisted.",
        });
      });
  };

  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  const handlePlantUpdated = (
    plantInstance: PlantInstance,
    previousPlantInstance: PlantInstance | null,
    planterId: string,
  ) => {
    const previousEventIds = new Set(
      (previousPlantInstance?.pestEvents ?? []).map((event) => event.id),
    );
    const addedPestEvents = (plantInstance.pestEvents ?? []).filter(
      (event) => !previousEventIds.has(event.id),
    );

    const journalEntries: GardenEvent[] = addedPestEvents.map((event) => ({
      id: `${event.type}-${event.id}`,
      type: event.type,
      plant: plantInstance.plant,
      date: event.date,
      gardenId: planterId,
      instanceId: plantInstance.instanceId,
      note: event.description,
    }));

    // Log an observation event when health state changes
    if (
      plantInstance.healthState !== (previousPlantInstance?.healthState ?? null) &&
      plantInstance.healthState != null
    ) {
      journalEntries.push({
        id: `observation-health-${Date.now()}-${Math.random()}`,
        type: "observation",
        plant: plantInstance.plant,
        date: new Date().toISOString(),
        gardenId: planterId,
        instanceId: plantInstance.instanceId,
        note: `Health state changed to: ${plantInstance.healthState}`,
      });
    }

    if (journalEntries.length === 0) return;

    setEvents((prev) => [...journalEntries, ...prev]);
    void Promise.all(
      journalEntries.map((entry) =>
        repositoryRef.current.saveEvent(entry as unknown as SchemaGardenEvent),
      ),
    )
      .then(() => dismissErrorToast(ERROR_TOAST_IDS.eventsSync))
      .catch((error) => {
        console.error("[Events] Failed to save journal entries:", error);
        notifyErrorToast({
          id: ERROR_TOAST_IDS.eventsSync,
          title: "Could not save journal entries",
          error,
          fallback: "The journal update may not be fully persisted.",
        });
      });
  };

  const handleCompleteSuggestion = (suggestion: Suggestion) => {
    // Map suggestion type → event type for the journal log.
    // "no_water" carries no positive action — skip journal logging entirely.
    if (suggestion.type === "no_water") return;

    const eventType: GardenEvent["type"] =
      suggestion.type === "water"
        ? "watered"
        : suggestion.type === "harvest"
          ? "harvested"
          : suggestion.type === "treatment"
            ? "treatment"
            : suggestion.type === "fertilize" ||
                suggestion.type === "compost" ||
                suggestion.type === "mulch"
              ? "composted"
              : suggestion.type === "weed"
                ? "weeded"
                : suggestion.type === "sow" ||
                    suggestion.type === "succession_sow"
                  ? "sown"
                  : suggestion.type === "pest_alert"
                    ? "pest"
                    : "observation"; // companion_conflict, disease_risk, frost_protect, prune, repot, thin_seedlings, harden_seedlings, end_of_season

    // Determine scope from suggestion shape
    const scope: GardenEvent["scope"] = suggestion.plant
      ? "plant"
      : suggestion.planterId
        ? "planter"
        : suggestion.areaId
          ? "area"
          : undefined;

    const completedEvent: GardenEvent = {
      id: `event-${Date.now()}-${Math.random()}`,
      type: eventType,
      plant: suggestion.plant,
      date: new Date().toISOString(),
      gardenId: suggestion.planterId,
      instanceId: suggestion.instanceId,
      note:
        suggestion.type === "treatment" ? suggestion.description : undefined,
      scope,
      areaId: suggestion.areaId,
      planterName: suggestion.planterName,
      areaName: suggestion.areaName,
    };
    setEvents((prev) => [completedEvent, ...prev]);
    void repositoryRef.current.saveEvent(
      completedEvent as unknown as SchemaGardenEvent,
    )
      .then(() => dismissErrorToast(ERROR_TOAST_IDS.eventsSync))
      .catch((error) => {
        notifyErrorToast({
          id: ERROR_TOAST_IDS.eventsSync,
          title: "Could not save completed suggestion",
          error,
          fallback: "The completed action may not be fully persisted.",
        });
      });
  };

  const handlePlanterAction = ({
    type,
    planterId,
    areaId,
    planterName,
    areaName,
    note,
  }: {
    type: GardenEvent["type"];
    planterId: string;
    areaId?: string;
    planterName?: string;
    areaName?: string;
    note?: string;
  }) => {
    const eventLog: GardenEvent = {
      id: `planter-${type}-${Date.now()}-${Math.random()}`,
      type,
      date: new Date().toISOString(),
      gardenId: planterId,
      note,
      scope: "planter",
      areaId,
      planterName,
      areaName,
    };
    setEvents((prev) => [eventLog, ...prev]);
    void repositoryRef.current.saveEvent(
      eventLog as unknown as SchemaGardenEvent,
    )
      .then(() => dismissErrorToast(ERROR_TOAST_IDS.eventsSync))
      .catch((error) => {
        notifyErrorToast({
          id: ERROR_TOAST_IDS.eventsSync,
          title: "Could not save planter action",
          error,
          fallback: "The planter action may not be fully persisted.",
        });
      });
  };

  const handleAreaAction = ({
    type,
    areaId,
    areaName,
    planterIds,
    planterNames,
    note,
  }: {
    type: GardenEvent["type"];
    areaId: string;
    areaName: string;
    planterIds: string[];
    planterNames: string[];
    note?: string;
  }) => {
    // Create one area-scope event to represent the whole-area action
    const areaEvent: GardenEvent = {
      id: `area-${type}-${Date.now()}-${Math.random()}`,
      type,
      date: new Date().toISOString(),
      note,
      scope: "area",
      areaId,
      areaName,
    };

    // Create one planter-scope event per planter so cooldown logic can use them
    const planterEvents: GardenEvent[] = planterIds.map((planterId, idx) => ({
      id: `planter-${type}-${Date.now()}-${Math.random()}-${idx}`,
      type,
      date: new Date().toISOString(),
      gardenId: planterId,
      note,
      scope: "planter" as const,
      areaId,
      planterName: planterNames[idx],
      areaName,
    }));

    const allEvents = [areaEvent, ...planterEvents];
    setEvents((prev) => [...allEvents, ...prev]);

    void Promise.all(
      allEvents.map((e) =>
        repositoryRef.current.saveEvent(e as unknown as SchemaGardenEvent),
      ),
    )
      .then(() => dismissErrorToast(ERROR_TOAST_IDS.eventsSync))
      .catch((error) => {
        notifyErrorToast({
          id: ERROR_TOAST_IDS.eventsSync,
          title: "Could not save area action",
          error,
          fallback: "The area action may not be fully persisted.",
        });
      });
  };

  return {
    harvestAlerts,
    handlePlantAdded,
    handlePlantRemoved,
    handlePlantUpdated,
    handleCompleteSuggestion,
    handlePlanterAction,
    handleAreaAction,
  };
}
