import path from "node:path";

import {
  formatTag,
  parseVersion,
  readJson,
  syncLockfileVersion,
  workspaceRoot,
  writeJson,
  writeText,
} from "./version-utils.mjs";

const rootPackageJsonPath = path.join(workspaceRoot, "package.json");
const rootPackageLockPath = path.join(workspaceRoot, "package-lock.json");
const backendPackageJsonPath = path.join(
  workspaceRoot,
  "backend",
  "package.json",
);
const backendPackageLockPath = path.join(
  workspaceRoot,
  "backend",
  "package-lock.json",
);
const appVersionModulePath = path.join(workspaceRoot, "app", "lib", "version.ts");

const rootPackageJson = readJson(rootPackageJsonPath);
const { version } = parseVersion(rootPackageJson.version);

if (rootPackageJson.version !== version) {
  rootPackageJson.version = version;
  writeJson(rootPackageJsonPath, rootPackageJson);
}

syncLockfileVersion(rootPackageLockPath, version);

const backendPackageJson = readJson(backendPackageJsonPath);
if (backendPackageJson.version !== version) {
  backendPackageJson.version = version;
  writeJson(backendPackageJsonPath, backendPackageJson);
}

syncLockfileVersion(backendPackageLockPath, version);

writeText(
  appVersionModulePath,
  `// Generated by scripts/version-sync.mjs. Do not edit manually.\nexport const APP_VERSION = "${formatTag(version)}" as const;\nexport const APP_VERSION_NUMBER = "${version}" as const;\n`,
);

console.log(`Synced version ${formatTag(version)}`);